baseURL = "https://usa-trip-blog.pages.dev/"
languageCode = "ja"
title = "ã‚¢ãƒ¡ãƒªã‚«æ¨ªæ–­ãƒ–ãƒ­ã‚°"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
    googleAnalyticsID = "G-KFYME843QE"
    [params.homeInfoParams]
        Title = "Hi there ğŸ‘‹"
        Content = "ã‚¢ãƒ¡ãƒªã‚«æ¨ªæ–­ãƒ–ãƒ­ã‚°ã¸ã‚ˆã†ã“ãï¼ã“ã“ã‹ã‚‰ãƒ«ãƒ¼ãƒˆæ¤œè¨ã‚„æº–å‚™ã‚’è¨˜éŒ²ã—ã¦ã„ãã¾ã™ã€‚"
